export function slugify(input: string) {
  const s = input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 28);
  return s || "app";
}

export function bundleIdFromTitle(title: string) {
  const parts = slugify(title).split("-").filter(Boolean).slice(0, 3);
  return `helix.kreluna.${parts.join("") || "app"}`;
}

export function expoFiles(input: {
  title: string;
  slug: string;
  html: string;
  bundleId: string;
  appleTeam?: string;
  liveUrl: string;
  platform: "ios" | "android";
}) {
  const scheme = input.slug.replace(/-/g, "");
  return {
    "README.md": `# ${input.title}

Native shell generated by Helix / Harbor.

## TestFlight (iOS)
1. npm i -g eas-cli && npm install
2. eas login
3. eas build --platform ios --profile production
4. eas submit --platform ios --latest

Apple Team: ${input.appleTeam || "(add your Team ID)"}
Bundle: ${input.bundleId}

## Google Play
eas build --platform android --profile production
eas submit --platform android --latest

Live web: ${input.liveUrl}
`,
    "package.json": JSON.stringify(
      {
        name: input.slug,
        version: "1.0.0",
        private: true,
        main: "index.js",
        scripts: {
          start: "expo start",
          ios: "expo run:ios",
          android: "expo run:android",
        },
        dependencies: {
          expo: "~52.0.0",
          react: "18.3.1",
          "react-native": "0.76.6",
          "react-native-webview": "13.12.5",
        },
      },
      null,
      2,
    ),
    "app.json": JSON.stringify(
      {
        expo: {
          name: input.title,
          slug: input.slug,
          scheme,
          version: "1.0.0",
          orientation: "portrait",
          userInterfaceStyle: "automatic",
          ios: {
            bundleIdentifier: input.bundleId,
            supportsTablet: true,
            appleTeamId: input.appleTeam || undefined,
          },
          android: { package: input.bundleId },
          extra: { liveUrl: input.liveUrl },
        },
      },
      null,
      2,
    ),
    "eas.json": JSON.stringify(
      {
        cli: { version: ">= 13.0.0" },
        build: {
          production: {
            ios: { resourceClass: "m-medium" },
            android: { buildType: "app-bundle" },
          },
          preview: { distribution: "internal" },
        },
        submit: { production: { ios: { appleTeamId: input.appleTeam || undefined } } },
      },
      null,
      2,
    ),
    "index.js": `import { registerRootComponent } from 'expo';
import App from './App';
registerRootComponent(App);
`,
    "App.js": `import { WebView } from 'react-native-webview';
const html = ${JSON.stringify(input.html)};
export default function App() {
  return (
    <WebView
      originWhitelist={['*']}
      source={{ html }}
      style={{ flex: 1 }}
      setSupportMultipleWindows={false}
      allowsInlineMediaPlayback
    />
  );
}
`,
    ".gitignore": "node_modules\n.expo\ndist\n",
  };
}

export function windowsFiles(input: { title: string; slug: string; html: string; liveUrl: string }) {
  const name = input.slug || "helix-app";
  return {
    "README.md": `# ${input.title} — desktop program

Generated by Helix / Cedar.

## Run on Windows, Mac or Linux
\`\`\`
npm install
npm start
\`\`\`

Opens a native window (Electron) with the program inside.

## Microsoft Store
1. Open ${input.liveUrl} in Edge → Apps → Install this site as an app.
2. Or package this folder with \`electron-builder\`.

Live preview: ${input.liveUrl}
`,
    "package.json": JSON.stringify(
      {
        name,
        version: "1.0.0",
        private: true,
        main: "main.js",
        scripts: {
          start: "electron .",
          pack: "electron-builder --win --mac --linux",
        },
        devDependencies: {
          electron: "^33.0.0",
          "electron-builder": "^25.1.8",
        },
        build: {
          appId: `helix.kreluna.${name.replace(/-/g, "")}`,
          productName: input.title,
          files: ["main.js", "index.html", "preload.js"],
          win: { target: "nsis" },
          mac: { target: "dmg" },
          linux: { target: "AppImage" },
        },
      },
      null,
      2,
    ),
    "main.js": `const { app, BrowserWindow } = require('electron');
const path = require('path');
function create() {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 900,
    minHeight: 600,
    title: ${JSON.stringify(input.title)},
    backgroundColor: '#070914',
    webPreferences: { preload: path.join(__dirname, 'preload.js') },
  });
  win.loadFile('index.html');
}
app.whenReady().then(create);
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) create(); });
`,
    "preload.js": `window.addEventListener('DOMContentLoaded', () => {});
`,
    "index.html": input.html,
    "manifest.json": JSON.stringify(
      {
        name: input.title,
        short_name: input.title.slice(0, 12),
        start_url: ".",
        display: "standalone",
        background_color: "#070914",
        theme_color: "#7C3AED",
      },
      null,
      2,
    ),
  };
}

export function withPwa(html: string, title: string, slug: string) {
  const manifest = {
    name: title,
    short_name: title.slice(0, 12),
    start_url: `.`,
    display: "standalone",
    background_color: "#070914",
    theme_color: "#7C3AED",
  };
  const tag = `<link rel="manifest" href="data:application/manifest+json,${encodeURIComponent(JSON.stringify(manifest))}"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-title" content="${title.replace(/"/g, "")}"/>
<meta name="mobile-web-app-capable" content="yes"/>`;
  if (/<head[^>]*>/i.test(html)) return html.replace(/<head[^>]*>/i, (m) => `${m}\n${tag}`);
  return tag + html;
}
