import type { Locale } from "@/lib/i18n-core";

export const FLAGSHIP_IDS = ["orbit-command", "neura", "synapse", "vanta", "arc-city", "morph", "studio-ledger", "pulse-booking", "foundry-erp", "mercedes-epoque", "italvia", "mini4wd-lab", "atelier-nova", "casa-verde", "lumen-clinic", "northstar-legal", "velora-commerce", "festival-onda"] as const;

export type FlagshipId = (typeof FLAGSHIP_IDS)[number];

type FlagshipCopy = {
  brand: string;
  title: string;
  kind: string;
  prompt: string;
  capability: string;
  proof: string;
  ui: Record<string, string>;
};

type FlagshipCopyTable = Record<FlagshipId, FlagshipCopy>;

export type ShowcaseLabels = {
  prompt: string;
  capability: string;
  proof: string;
  all: string;
  apps: string;
  sites: string;
  appsTitle: string;
  appsLead: string;
  sitesTitle: string;
  sitesLead: string;
  projectsCount: string;
  archiveTitle: string;
  archiveLead: string;
  archiveOpen: string;
};

const en: FlagshipCopyTable = {
  "orbit-command": {
    brand: "ORBIT COMMAND",
    title: "Orbital mission control",
    kind: "Space systems twin",
    prompt: "Build a mission-control digital twin for a small satellite fleet, with orbit planning and live telemetry.",
    capability: "Spatial telemetry, fleet selection, layer controls, time scrub and maneuver planning.",
    proof: "Live app thumbnail · 12 local controls · offline canvas telemetry",
    ui: {
      eyebrow: "MISSION CONTROL / LOW EARTH ORBIT",
      live: "LIVE LINK",
      missionTime: "MISSION TIME",
      fleet: "FLEET",
      telemetry: "TELEMETRY",
      timeline: "ORBIT TIMELINE",
      pause: "Pause",
      resume: "Resume",
      ground: "Ground track",
      debris: "Debris field",
      paths: "Orbit paths",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      plan: "Plan burn",
      commit: "Commit maneuver",
      cancel: "Cancel plan",
      nominal: "Nominal",
      contact: "Next contact",
      fuel: "Fuel",
      inclination: "Inclination",
      altitude: "Altitude",
      selected: "Selected vehicle",
      noticePlan: "Maneuver corridor plotted.",
      noticeCommitted: "Simulation updated; no command was sent.",
      noticeCancelled: "Maneuver plan cleared.",
      sat1: "Astra-7",
      sat2: "Vega-2",
      sat3: "Kite-4",
      station: "Kiruna ground station",
    },
  },
  neura: {
    brand: "NEURA",
    title: "Neural systems observatory",
    kind: "Biotech visualization demo",
    prompt: "Create a non-clinical neural digital-twin demonstrator for exploring regions, signals and simulated cohorts.",
    capability: "Scientific visualization, region comparison, signal timeline, annotations and snapshots.",
    proof: "Live app thumbnail · 10 local controls · explicitly non-clinical simulation",
    ui: {
      eyebrow: "NEURAL SYSTEMS OBSERVATORY",
      demoNotice: "RESEARCH DEMO · NOT FOR CLINICAL USE",
      study: "Study N-204",
      overview: "Overview",
      signals: "Signals",
      cohort: "Cohort",
      compare: "Compare",
      region: "REGION",
      cortex: "Cortex",
      stem: "Brainstem",
      network: "Network",
      baseline: "Baseline",
      stimulus: "Stimulus",
      recovery: "Recovery",
      play: "Run simulation",
      pause: "Pause",
      snapshot: "Capture snapshot",
      annotate: "Add annotation",
      reset: "Reset study",
      biomarkers: "SIMULATED MARKERS",
      coherence: "Coherence",
      response: "Response",
      symmetry: "Symmetry",
      activity: "REGIONAL ACTIVITY",
      stable: "Stable simulated pattern",
      noteSnapshot: "Snapshot added to the study log.",
      noteAnnotation: "Annotation anchored at the current sample.",
      noteReset: "Study view restored to baseline.",
      timeline: "SAMPLE TIMELINE",
      sample: "Sample",
    },
  },
  synapse: {
    brand: "SYNAPSE",
    title: "Collaborative intelligence workspace",
    kind: "AI collaboration workspace",
    prompt: "Design a premium collaborative canvas where a team can connect research, decisions, tasks and agent activity.",
    capability: "Knowledge canvas, typed nodes, search, filters, activity stream and relationship editing.",
    proof: "Live app thumbnail · 11 local controls · editable in-memory workspace",
    ui: {
      eyebrow: "COLLABORATIVE INTELLIGENCE",
      workspace: "Helios launch workspace",
      canvas: "Canvas",
      documents: "Documents",
      activity: "Activity",
      search: "Search the workspace",
      addNode: "New node",
      focus: "Focus",
      align: "Align",
      connect: "Connect",
      filterAll: "All",
      filterDecision: "Decisions",
      filterTask: "Tasks",
      brief: "Launch brief",
      research: "Audience research",
      direction: "Product direction",
      prototype: "Prototype review",
      decision: "Decision",
      task: "Task",
      note: "Note",
      owner: "Owner",
      due: "Due",
      newNode: "A new task was added to the canvas.",
      connected: "Selected ideas are now connected.",
      aligned: "Visible nodes aligned to the working grid.",
      focused: "Focus mode isolates the selected thread.",
      searchResult: "matching workspace items",
      activityOn: "Activity panel opened.",
      activityOff: "Activity panel closed.",
    },
  },
  vanta: {
    brand: "VANTA",
    title: "Market risk terminal",
    kind: "Simulated trading workstation",
    prompt: "Build a dense professional market terminal with charting, watchlists, risk controls and simulated orders.",
    capability: "Streaming-style chart, watchlist, depth, positions, risk limits and paper-order workflow.",
    proof: "Live app thumbnail · 13 local controls · all trading explicitly simulated",
    ui: {
      eyebrow: "MARKET RISK TERMINAL",
      simulated: "SIMULATED DATA · NO EXECUTION",
      markets: "MARKETS",
      blotter: "BLOTTER",
      risk: "RISK",
      watchlist: "WATCHLIST",
      symbol: "SYMBOL",
      last: "LAST",
      change: "CHANGE",
      range1d: "1D",
      range1w: "1W",
      range1m: "1M",
      candles: "Candles",
      depth: "Depth",
      positions: "POSITIONS",
      orders: "ORDERS",
      buy: "BUY",
      sell: "SELL",
      quantity: "Quantity",
      limit: "Limit price",
      simulate: "Simulate order",
      cancel: "Cancel pending",
      exposure: "NET EXPOSURE",
      var: "SIMULATED VaR",
      pnl: "PAPER P&L",
      orderReady: "Order ticket ready for paper simulation.",
      orderSent: "Paper order added to the blotter; nothing was transmitted.",
      orderCancelled: "Pending paper order cancelled.",
      chart: "PRICE / VOLUME",
      book: "ORDER BOOK",
      desk: "EUROPE / GROWTH DESK",
    },
  },
  "arc-city": {
    brand: "ARC CITY",
    title: "Urban systems twin",
    kind: "Smart-city digital twin",
    prompt: "Create a map-first city twin for exploring traffic, energy and environmental layers across districts and time.",
    capability: "Layered city map, district inspection, time simulation, alerts and infrastructure metrics.",
    proof: "Live app thumbnail · 12 local controls · offline SVG city model",
    ui: {
      eyebrow: "URBAN SYSTEMS TWIN",
      twin: "ARC / CITY 04",
      layers: "LAYERS",
      traffic: "Traffic",
      energy: "Energy",
      air: "Air quality",
      water: "Water",
      transit: "Transit",
      districts: "DISTRICTS",
      harbor: "Harbor",
      central: "Central",
      north: "North grid",
      timeline: "CITY TIMELINE",
      live: "Live",
      simulate: "Simulate evening",
      pause: "Pause",
      resume: "Resume",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      alerts: "ALERTS",
      clear: "Clear resolved",
      camera: "Recenter map",
      inspect: "Inspect district",
      demand: "Energy demand",
      flow: "Traffic flow",
      quality: "Air index",
      occupancy: "Transit load",
      selected: "Selected district",
      eventTraffic: "Traffic layer highlighted.",
      eventEnergy: "Evening demand scenario loaded.",
      eventAir: "Air-quality sensors selected.",
      eventCleared: "Resolved alerts removed.",
      morning: "Morning",
      evening: "Evening",
      now: "Now",
    },
  },
  morph: {
    brand: "MORPH",
    title: "Material configurator",
    kind: "Cinematic 3D-style configurator",
    prompt: "Design a cinematic automotive configurator with material, cabin, wheel, lighting and camera controls.",
    capability: "Product-stage visualization, materials, specifications, camera rotation, lighting and saved configuration.",
    proof: "Live app thumbnail · 14 local controls · CSS/SVG product stage without stock imagery",
    ui: {
      eyebrow: "PHYSICAL PRODUCT CONFIGURATOR",
      configurator: "M-01 / SERIES",
      model: "MODEL",
      material: "MATERIAL",
      cabin: "CABIN",
      stance: "STANCE",
      studio: "Studio",
      road: "Road",
      detail: "Detail",
      lights: "Lights",
      rotate: "Rotate view",
      save: "Save specification",
      saved: "Specification saved locally for this demo.",
      reset: "Reset",
      graphite: "Graphite",
      pearl: "Pearl",
      copper: "Copper",
      cobalt: "Cobalt",
      wheelAero: "Aero 21",
      wheelTrack: "Track 22",
      interiorStone: "Stone",
      interiorInk: "Ink",
      interiorSaddle: "Saddle",
      power: "Power",
      range: "Range",
      sprint: "0–100 km/h",
      viewFront: "Front",
      viewSide: "Profile",
      viewRear: "Rear",
      hotspot: "Open material detail",
      selection: "CURRENT SPECIFICATION",
      spec: "M-01 Dual Motor",
      body: "Body",
      wheel: "Wheel",
      interior: "Interior",
      noticeReset: "Factory configuration restored.",
    },
  },
  "studio-ledger": {
    brand: "STUDIO LEDGER",
    title: "Professional practice command desk",
    kind: "Practice management app",
    prompt: "Build a premium management workspace for an accounting or professional practice, covering clients, deadlines, documents and invoices.",
    capability: "Client portfolio, compliance calendar, document queue, invoicing overview and focused daily worklist.",
    proof: "Live app thumbnail · 12 local controls · offline practice workflow",
    ui: {},
  },
  "pulse-booking": {
    brand: "PULSE BOOKING",
    title: "Appointments and capacity planner",
    kind: "Booking operations app",
    prompt: "Create a polished appointment and capacity planner for a clinic, salon or professional studio with calendar, staff and client flows.",
    capability: "Interactive calendar, staff availability, service filters, appointment details and wait-list controls.",
    proof: "Live app thumbnail · 11 local controls · in-memory booking workflow",
    ui: {},
  },
  "foundry-erp": {
    brand: "FOUNDRY ERP",
    title: "Business operations system",
    kind: "ERP and management software",
    prompt: "Design a high-end management system for orders, inventory, customers, invoices and operational performance.",
    capability: "Order pipeline, stock health, CRM records, invoice status, alerts and operational KPIs.",
    proof: "Live app thumbnail · 13 local controls · offline ERP simulation",
    ui: {},
  },
  "mercedes-epoque": {
    brand: "MERCEDES ÉPOQUE",
    title: "Classic and modern Mercedes hire",
    kind: "Automotive collection website",
    prompt: "Build Mercedes Époque, a refined hire site for classic and modern Mercedes with historic and contemporary cars, search and a demo availability request.",
    capability: "Era filters, searchable collection, car details, stay length and an honest demo booking request.",
    proof: "Live site thumbnail · 11 local controls · museum car photography, demo booking",
    ui: {},
  },
  italvia: {
    brand: "ITALVIA",
    title: "Italy–Poland property concierge",
    kind: "Real-estate concierge website",
    prompt: "Build Italvia, a bilingual Italy–Poland property concierge with seasonal honesty, all-in cost, a safety dossier and a personal agent thread.",
    capability: "Seasonal house view, curated homes, all-in cost, dossier checks and an agent message demo.",
    proof: "Live site thumbnail · 10 local controls · Italian road photography, offline concierge",
    ui: {},
  },
  "mini4wd-lab": {
    brand: "MINI4WD LAB",
    title: "Build, cut carbon, race",
    kind: "Hobby workshop website",
    prompt: "Build Mini4WD Lab, a workshop guide to assemble a Mini 4WD, cut carbon parts and launch the car on a jump track.",
    capability: "Goal presets, setup parts, carbon steps and an in-memory jump test.",
    proof: "Live site thumbnail · 12 local controls · neon track photography, offline workshop",
    ui: {},
  },
  "atelier-nova": {
    brand: "ATELIER NOVA",
    title: "Architecture and design portfolio",
    kind: "Creative studio website",
    prompt: "Create an editorial architecture and interior-design studio website with projects, approach, journal and consultation enquiry.",
    capability: "Immersive portfolio, project filtering, editorial storytelling and consultation interaction.",
    proof: "Live site thumbnail · 10 local controls · CSS-built architectural imagery",
    ui: {},
  },
  "casa-verde": {
    brand: "CASA VERDE",
    title: "Slow hospitality retreat",
    kind: "Hospitality website",
    prompt: "Build an atmospheric hospitality website for a countryside retreat with rooms, dining, experiences and availability enquiry.",
    capability: "Room storytelling, stay configurator, experience gallery, dining details and booking enquiry.",
    proof: "Live site thumbnail · 11 local controls · honest demo booking flow",
    ui: {},
  },
  "lumen-clinic": {
    brand: "LUMEN CLINIC",
    title: "Private clinic and care pathways",
    kind: "Healthcare service website",
    prompt: "Design a calm private-clinic website that explains specialties, doctors, care pathways and appointment requests clearly.",
    capability: "Specialty navigation, doctor profiles, pathway explainer, accessibility controls and appointment request.",
    proof: "Live site thumbnail · 12 local controls · explicitly informational medical demo",
    ui: {},
  },
  "northstar-legal": {
    brand: "NORTHSTAR LEGAL",
    title: "Professional advisory firm",
    kind: "Legal and advisory website",
    prompt: "Create a trusted legal and professional-advisory website with practices, people, insights and confidential enquiry.",
    capability: "Practice-area explorer, partner profiles, insight filters, office details and enquiry flow.",
    proof: "Live site thumbnail · 10 local controls · privacy-aware enquiry demo",
    ui: {},
  },
  "velora-commerce": {
    brand: "VELORA OBJECTS",
    title: "Premium product collection",
    kind: "Commerce website",
    prompt: "Build a refined direct-to-consumer product site with collections, material stories, product configuration and a demo cart.",
    capability: "Collection filters, product story, colour selection, quantity, cart drawer and shipping estimator.",
    proof: "Live site thumbnail · 13 local controls · simulated cart with no checkout",
    ui: {},
  },
  "festival-onda": {
    brand: "ONDA FESTIVAL",
    title: "Culture and live-programme site",
    kind: "Festival and event website",
    prompt: "Create a bold cultural-festival website with programme, stages, artists, schedule builder and ticket information.",
    capability: "Programme filters, stage map, artist cards, personal schedule and ticket-information flow.",
    proof: "Live site thumbnail · 12 local controls · offline programme planner",
    ui: {},
  },
};

function translated(
  base: FlagshipCopyTable,
  values: Partial<Record<FlagshipId, Partial<FlagshipCopy> & { ui?: Record<string, string> }>>,
): FlagshipCopyTable {
  return Object.fromEntries(
    FLAGSHIP_IDS.map((id) => {
      const next = values[id];
      return [
        id,
        {
          ...base[id],
          ...next,
          ui: { ...base[id].ui, ...(next?.ui ?? {}) },
        },
      ];
    }),
  ) as FlagshipCopyTable;
}

const it = translated(en, {
  "orbit-command": {
    title: "Controllo missione orbitale",
    kind: "Gemello digitale spaziale",
    prompt: "Crea un gemello digitale per il controllo missione di una piccola flotta satellitare, con pianificazione orbitale e telemetria live.",
    capability: "Telemetria spaziale, selezione flotta, livelli, timeline e pianificazione manovre.",
    proof: "Anteprima app live · 12 controlli locali · telemetria canvas offline",
    ui: { eyebrow: "CONTROLLO MISSIONE / ORBITA BASSA", live: "COLLEGAMENTO LIVE", missionTime: "TEMPO MISSIONE", fleet: "FLOTTA", telemetry: "TELEMETRIA", timeline: "TIMELINE ORBITALE", pause: "Pausa", resume: "Riprendi", ground: "Traccia a terra", debris: "Campo detriti", paths: "Orbite", zoomIn: "Ingrandisci", zoomOut: "Riduci", plan: "Pianifica accensione", commit: "Conferma manovra", cancel: "Annulla piano", nominal: "Nominale", contact: "Prossimo contatto", fuel: "Carburante", inclination: "Inclinazione", altitude: "Altitudine", selected: "Veicolo selezionato", noticePlan: "Corridoio di manovra tracciato.", noticeCommitted: "Simulazione aggiornata; nessun comando inviato.", noticeCancelled: "Piano di manovra rimosso.", station: "Stazione di terra Kiruna" },
  },
  neura: {
    title: "Osservatorio dei sistemi neurali",
    kind: "Demo di visualizzazione biotech",
    prompt: "Crea un dimostratore non clinico di gemello neurale per esplorare regioni, segnali e coorti simulate.",
    capability: "Visualizzazione scientifica, confronto regioni, timeline dei segnali, annotazioni e snapshot.",
    proof: "Anteprima app live · 10 controlli locali · simulazione esplicitamente non clinica",
    ui: { eyebrow: "OSSERVATORIO DEI SISTEMI NEURALI", demoNotice: "DEMO DI RICERCA · NON PER USO CLINICO", study: "Studio N-204", overview: "Panoramica", signals: "Segnali", cohort: "Coorte", compare: "Confronta", region: "REGIONE", cortex: "Corteccia", stem: "Tronco encefalico", network: "Rete", baseline: "Baseline", stimulus: "Stimolo", recovery: "Recupero", play: "Avvia simulazione", pause: "Pausa", snapshot: "Cattura snapshot", annotate: "Aggiungi nota", reset: "Reimposta studio", biomarkers: "INDICATORI SIMULATI", coherence: "Coerenza", response: "Risposta", symmetry: "Simmetria", activity: "ATTIVITÀ REGIONALE", stable: "Pattern simulato stabile", noteSnapshot: "Snapshot aggiunto al registro dello studio.", noteAnnotation: "Nota ancorata al campione corrente.", noteReset: "Vista dello studio ripristinata alla baseline.", timeline: "TIMELINE CAMPIONI", sample: "Campione" },
  },
  synapse: {
    title: "Spazio di intelligenza collaborativa",
    kind: "Workspace di collaborazione AI",
    prompt: "Progetta un canvas collaborativo premium dove collegare ricerca, decisioni, attività e lavoro degli agenti.",
    capability: "Canvas di conoscenza, nodi tipizzati, ricerca, filtri, attività e modifica delle relazioni.",
    proof: "Anteprima app live · 11 controlli locali · workspace modificabile in memoria",
    ui: { eyebrow: "INTELLIGENZA COLLABORATIVA", workspace: "Workspace lancio Helios", canvas: "Canvas", documents: "Documenti", activity: "Attività", search: "Cerca nel workspace", addNode: "Nuovo nodo", focus: "Focus", align: "Allinea", connect: "Collega", filterAll: "Tutto", filterDecision: "Decisioni", filterTask: "Attività", brief: "Brief di lancio", research: "Ricerca pubblico", direction: "Direzione prodotto", prototype: "Revisione prototipo", decision: "Decisione", task: "Attività", note: "Nota", owner: "Responsabile", due: "Scadenza", newNode: "Una nuova attività è stata aggiunta al canvas.", connected: "Le idee selezionate ora sono collegate.", aligned: "Nodi visibili allineati alla griglia.", focused: "La modalità focus isola il filo selezionato.", searchResult: "elementi corrispondenti", activityOn: "Pannello attività aperto.", activityOff: "Pannello attività chiuso." },
  },
  vanta: {
    title: "Terminale rischio mercati",
    kind: "Postazione trading simulata",
    prompt: "Crea un terminale professionale denso con grafici, watchlist, controlli rischio e ordini simulati.",
    capability: "Grafico dinamico, watchlist, profondità, posizioni, limiti rischio e ordini paper.",
    proof: "Anteprima app live · 13 controlli locali · trading interamente simulato",
    ui: { eyebrow: "TERMINALE RISCHIO MERCATI", simulated: "DATI SIMULATI · NESSUNA ESECUZIONE", markets: "MERCATI", blotter: "REGISTRO", risk: "RISCHIO", watchlist: "WATCHLIST", symbol: "SIMBOLO", last: "ULTIMO", change: "VARIAZIONE", candles: "Candele", depth: "Profondità", positions: "POSIZIONI", orders: "ORDINI", buy: "COMPRA", sell: "VENDI", quantity: "Quantità", limit: "Prezzo limite", simulate: "Simula ordine", cancel: "Annulla pendente", exposure: "ESPOSIZIONE NETTA", var: "VaR SIMULATO", pnl: "P&L PAPER", orderReady: "Ticket pronto per la simulazione paper.", orderSent: "Ordine paper aggiunto al registro; nulla è stato trasmesso.", orderCancelled: "Ordine paper pendente annullato.", chart: "PREZZO / VOLUME", book: "BOOK ORDINI", desk: "EUROPA / GROWTH DESK" },
  },
  "arc-city": {
    title: "Gemello dei sistemi urbani",
    kind: "Gemello digitale smart city",
    prompt: "Crea un gemello urbano map-first per esplorare traffico, energia e ambiente nei quartieri e nel tempo.",
    capability: "Mappa urbana a livelli, ispezione quartieri, simulazione temporale, alert e metriche infrastrutturali.",
    proof: "Anteprima app live · 12 controlli locali · modello urbano SVG offline",
    ui: { eyebrow: "GEMELLO DEI SISTEMI URBANI", layers: "LIVELLI", traffic: "Traffico", energy: "Energia", air: "Qualità aria", water: "Acqua", transit: "Trasporto", districts: "QUARTIERI", harbor: "Porto", central: "Centro", north: "Rete nord", timeline: "TIMELINE CITTÀ", live: "Live", simulate: "Simula sera", pause: "Pausa", resume: "Riprendi", zoomIn: "Ingrandisci", zoomOut: "Riduci", alerts: "AVVISI", clear: "Rimuovi risolti", camera: "Ricentra mappa", inspect: "Ispeziona quartiere", demand: "Domanda energia", flow: "Flusso traffico", quality: "Indice aria", occupancy: "Carico trasporto", selected: "Quartiere selezionato", eventTraffic: "Livello traffico evidenziato.", eventEnergy: "Scenario domanda serale caricato.", eventAir: "Sensori qualità aria selezionati.", eventCleared: "Avvisi risolti rimossi.", morning: "Mattina", evening: "Sera", now: "Ora" },
  },
  morph: {
    title: "Configuratore di materiali",
    kind: "Configuratore cinematico in stile 3D",
    prompt: "Progetta un configuratore automotive cinematico con controlli per materiali, abitacolo, ruote, luci e camera.",
    capability: "Visualizzazione prodotto, materiali, specifiche, rotazione camera, illuminazione e configurazione salvata.",
    proof: "Anteprima app live · 14 controlli locali · prodotto CSS/SVG senza foto stock",
    ui: { eyebrow: "CONFIGURATORE DI PRODOTTO FISICO", configurator: "M-01 / SERIE", model: "MODELLO", material: "MATERIALE", cabin: "ABITACOLO", stance: "ASSETTO", studio: "Studio", road: "Strada", detail: "Dettaglio", lights: "Luci", rotate: "Ruota vista", save: "Salva specifica", saved: "Specifica salvata localmente per questa demo.", reset: "Reimposta", graphite: "Grafite", pearl: "Perla", copper: "Rame", cobalt: "Cobalto", wheelAero: "Aero 21", wheelTrack: "Track 22", interiorStone: "Pietra", interiorInk: "Inchiostro", interiorSaddle: "Cuoio", power: "Potenza", range: "Autonomia", sprint: "0–100 km/h", viewFront: "Fronte", viewSide: "Profilo", viewRear: "Retro", hotspot: "Apri dettaglio materiale", selection: "SPECIFICA CORRENTE", spec: "M-01 Dual Motor", body: "Carrozzeria", wheel: "Ruota", interior: "Interni", noticeReset: "Configurazione di fabbrica ripristinata." },
  },
  "studio-ledger": {
    title: "Cabina di regia per studi professionali",
    kind: "Gestionale per studi",
    prompt: "Crea un gestionale premium per uno studio commercialista o professionale, con clienti, scadenze, documenti e fatture.",
    capability: "Portafoglio clienti, calendario adempimenti, documenti, situazione fatture e agenda operativa giornaliera.",
    proof: "Anteprima app live · 12 controlli locali · flusso studio offline",
  },
  "pulse-booking": {
    title: "Agenda appuntamenti e capacità",
    kind: "App per prenotazioni",
    prompt: "Crea un’agenda appuntamenti elegante per cliniche, saloni o studi con calendario, personale e flussi cliente.",
    capability: "Calendario interattivo, disponibilità staff, filtri servizio, dettaglio appuntamento e lista d’attesa.",
    proof: "Anteprima app live · 11 controlli locali · prenotazioni solo in memoria",
  },
  "foundry-erp": {
    title: "Sistema operativo aziendale",
    kind: "ERP e software gestionale",
    prompt: "Progetta un gestionale di alto livello per ordini, magazzino, clienti, fatture e andamento operativo.",
    capability: "Pipeline ordini, salute scorte, CRM, stato fatture, alert e indicatori operativi.",
    proof: "Anteprima app live · 13 controlli locali · simulazione ERP offline",
  },
  "mercedes-epoque": {
    title: "Noleggio Mercedes classiche e moderne",
    kind: "Sito per collezione auto",
    prompt: "Crea Mercedes Époque, un sito di noleggio per Mercedes classiche e moderne, con filtri d’epoca, ricerca e richiesta disponibilità demo.",
    capability: "Filtri epoca, collezione ricercabile, scheda auto, durata e richiesta prenotazione demo.",
    proof: "Anteprima sito live · 11 controlli locali · fotografia da museo, prenotazione demo",
  },
  italvia: {
    title: "Concierge immobiliare Italia–Polonia",
    kind: "Sito concierge immobiliare",
    prompt: "Crea Italvia, un concierge immobiliare Italia–Polonia con onestà stagionale, costo complessivo, dossier di sicurezza e agente personale.",
    capability: "Vista estate/inverno, case curate, costo complessivo, dossier e messaggio all’agente.",
    proof: "Anteprima sito live · 10 controlli locali · strade italiane in fotografia, concierge offline",
  },
  "mini4wd-lab": {
    title: "Costruisci, taglia il carbonio, prova in pista",
    kind: "Sito-laboratorio hobby",
    prompt: "Crea Mini4WD Lab, una guida per montare una Mini 4WD, tagliare il carbonio e lanciarla sul salto.",
    capability: "Obiettivi, pezzi d’assetto, passi carbonio e prova salto in memoria.",
    proof: "Anteprima sito live · 12 controlli locali · pista al neon fotografica, laboratorio offline",
  },
  "atelier-nova": {
    title: "Portfolio di architettura e design",
    kind: "Sito per studio creativo",
    prompt: "Crea un sito editoriale per uno studio di architettura e interior design con progetti, metodo, journal e consulenze.",
    capability: "Portfolio immersivo, filtri progetti, racconto editoriale e richiesta consulenza.",
    proof: "Anteprima sito live · 10 controlli locali · immagini architettoniche in CSS",
  },
  "casa-verde": {
    title: "Ospitalità lenta nella natura",
    kind: "Sito hospitality",
    prompt: "Crea un sito d’atmosfera per un retreat di campagna con camere, cucina, esperienze e richiesta disponibilità.",
    capability: "Racconto camere, configuratore soggiorno, esperienze, ristorazione e richiesta prenotazione.",
    proof: "Anteprima sito live · 11 controlli locali · prenotazione demo trasparente",
  },
  "lumen-clinic": {
    title: "Clinica privata e percorsi di cura",
    kind: "Sito per servizi sanitari",
    prompt: "Progetta un sito rassicurante per una clinica privata con specialità, medici, percorsi e richiesta appuntamento.",
    capability: "Navigazione specialità, profili medici, percorsi, accessibilità e richiesta appuntamento.",
    proof: "Anteprima sito live · 12 controlli locali · demo medica solo informativa",
  },
  "northstar-legal": {
    title: "Studio legale e consulenza professionale",
    kind: "Sito per professionisti",
    prompt: "Crea un sito autorevole per uno studio legale e di consulenza con aree, persone, approfondimenti e contatto riservato.",
    capability: "Aree di attività, profili partner, filtri insight, sedi e richiesta riservata.",
    proof: "Anteprima sito live · 10 controlli locali · contatto demo attento alla privacy",
  },
  "velora-commerce": {
    title: "Collezione di prodotto premium",
    kind: "Sito e-commerce",
    prompt: "Crea un e-commerce raffinato con collezioni, materiali, configurazione prodotto e carrello dimostrativo.",
    capability: "Filtri collezione, racconto prodotto, scelta colore, quantità, carrello e stima spedizione.",
    proof: "Anteprima sito live · 13 controlli locali · carrello simulato senza checkout",
  },
  "festival-onda": {
    title: "Cultura e programma dal vivo",
    kind: "Sito per festival ed eventi",
    prompt: "Crea un sito culturale deciso con programma, palchi, artisti, agenda personale e informazioni biglietti.",
    capability: "Filtri programma, mappa palchi, schede artisti, agenda personale e informazioni biglietti.",
    proof: "Anteprima sito live · 12 controlli locali · agenda festival offline",
  },
});

const es = translated(en, {
  "orbit-command": { title: "Control de misión orbital", kind: "Gemelo de sistemas espaciales", prompt: "Crea un gemelo digital de control de misión para una pequeña flota de satélites, con planificación orbital y telemetría en vivo.", capability: "Telemetría espacial, selección de flota, capas, línea temporal y planificación de maniobras.", proof: "Vista previa en vivo · 12 controles locales · telemetría canvas sin red", ui: { eyebrow: "CONTROL DE MISIÓN / ÓRBITA BAJA", live: "ENLACE ACTIVO", missionTime: "TIEMPO DE MISIÓN", fleet: "FLOTA", telemetry: "TELEMETRÍA", timeline: "LÍNEA ORBITAL", pause: "Pausar", resume: "Reanudar", ground: "Trayectoria terrestre", debris: "Campo de residuos", paths: "Órbitas", zoomIn: "Acercar", zoomOut: "Alejar", plan: "Planificar impulso", commit: "Confirmar maniobra", cancel: "Cancelar plan", nominal: "Nominal", contact: "Próximo contacto", fuel: "Combustible", inclination: "Inclinación", altitude: "Altitud", selected: "Vehículo seleccionado", noticePlan: "Corredor de maniobra trazado.", noticeCommitted: "Simulación actualizada; no se envió ningún comando.", noticeCancelled: "Plan de maniobra eliminado.", station: "Estación terrestre de Kiruna" } },
  neura: { title: "Observatorio de sistemas neuronales", kind: "Demo de visualización biotech", prompt: "Crea un demostrador no clínico de gemelo neuronal para explorar regiones, señales y cohortes simuladas.", capability: "Visualización científica, comparación regional, línea de señales, anotaciones y capturas.", proof: "Vista previa en vivo · 10 controles locales · simulación no clínica explícita", ui: { eyebrow: "OBSERVATORIO DE SISTEMAS NEURONALES", demoNotice: "DEMO DE INVESTIGACIÓN · NO PARA USO CLÍNICO", study: "Estudio N-204", overview: "Resumen", signals: "Señales", cohort: "Cohorte", compare: "Comparar", region: "REGIÓN", cortex: "Corteza", stem: "Tronco cerebral", network: "Red", baseline: "Base", stimulus: "Estímulo", recovery: "Recuperación", play: "Ejecutar simulación", pause: "Pausar", snapshot: "Capturar imagen", annotate: "Añadir anotación", reset: "Restablecer estudio", biomarkers: "MARCADORES SIMULADOS", coherence: "Coherencia", response: "Respuesta", symmetry: "Simetría", activity: "ACTIVIDAD REGIONAL", stable: "Patrón simulado estable", noteSnapshot: "Captura añadida al registro del estudio.", noteAnnotation: "Anotación fijada en la muestra actual.", noteReset: "Vista restaurada a la línea base.", timeline: "LÍNEA DE MUESTRAS", sample: "Muestra" } },
  synapse: { title: "Espacio de inteligencia colaborativa", kind: "Workspace de colaboración IA", prompt: "Diseña un canvas colaborativo premium para conectar investigación, decisiones, tareas y actividad de agentes.", capability: "Canvas de conocimiento, nodos tipados, búsqueda, filtros, actividad y relaciones editables.", proof: "Vista previa en vivo · 11 controles locales · workspace editable en memoria", ui: { eyebrow: "INTELIGENCIA COLABORATIVA", workspace: "Workspace de lanzamiento Helios", canvas: "Canvas", documents: "Documentos", activity: "Actividad", search: "Buscar en el workspace", addNode: "Nuevo nodo", focus: "Enfocar", align: "Alinear", connect: "Conectar", filterAll: "Todo", filterDecision: "Decisiones", filterTask: "Tareas", brief: "Brief de lanzamiento", research: "Investigación de audiencia", direction: "Dirección de producto", prototype: "Revisión de prototipo", decision: "Decisión", task: "Tarea", note: "Nota", owner: "Responsable", due: "Fecha", newNode: "Se añadió una nueva tarea al canvas.", connected: "Las ideas seleccionadas están conectadas.", aligned: "Nodos visibles alineados a la cuadrícula.", focused: "El modo foco aísla el hilo seleccionado.", searchResult: "elementos coincidentes", activityOn: "Panel de actividad abierto.", activityOff: "Panel de actividad cerrado." } },
  vanta: { title: "Terminal de riesgo de mercado", kind: "Estación de trading simulada", prompt: "Crea un terminal profesional denso con gráficos, watchlist, controles de riesgo y órdenes simuladas.", capability: "Gráfico dinámico, watchlist, profundidad, posiciones, límites de riesgo y órdenes paper.", proof: "Vista previa en vivo · 13 controles locales · trading completamente simulado", ui: { eyebrow: "TERMINAL DE RIESGO DE MERCADO", simulated: "DATOS SIMULADOS · SIN EJECUCIÓN", markets: "MERCADOS", blotter: "REGISTRO", risk: "RIESGO", watchlist: "WATCHLIST", symbol: "SÍMBOLO", last: "ÚLTIMO", change: "CAMBIO", candles: "Velas", depth: "Profundidad", positions: "POSICIONES", orders: "ÓRDENES", buy: "COMPRAR", sell: "VENDER", quantity: "Cantidad", limit: "Precio límite", simulate: "Simular orden", cancel: "Cancelar pendiente", exposure: "EXPOSICIÓN NETA", var: "VaR SIMULADO", pnl: "P&L PAPER", orderReady: "Ticket listo para simulación paper.", orderSent: "Orden paper añadida; no se transmitió nada.", orderCancelled: "Orden paper pendiente cancelada.", chart: "PRECIO / VOLUMEN", book: "LIBRO DE ÓRDENES", desk: "EUROPA / GROWTH DESK" } },
  "arc-city": { title: "Gemelo de sistemas urbanos", kind: "Gemelo digital de ciudad", prompt: "Crea un gemelo urbano centrado en el mapa para explorar tráfico, energía y ambiente por distrito y tiempo.", capability: "Mapa urbano por capas, inspección de distritos, simulación temporal, alertas y métricas.", proof: "Vista previa en vivo · 12 controles locales · modelo urbano SVG sin red", ui: { eyebrow: "GEMELO DE SISTEMAS URBANOS", layers: "CAPAS", traffic: "Tráfico", energy: "Energía", air: "Calidad del aire", water: "Agua", transit: "Transporte", districts: "DISTRITOS", harbor: "Puerto", central: "Centro", north: "Red norte", timeline: "LÍNEA DE CIUDAD", live: "En vivo", simulate: "Simular tarde", pause: "Pausar", resume: "Reanudar", zoomIn: "Acercar", zoomOut: "Alejar", alerts: "ALERTAS", clear: "Quitar resueltas", camera: "Centrar mapa", inspect: "Inspeccionar distrito", demand: "Demanda energética", flow: "Flujo de tráfico", quality: "Índice del aire", occupancy: "Carga de transporte", selected: "Distrito seleccionado", eventTraffic: "Capa de tráfico resaltada.", eventEnergy: "Escenario de demanda vespertina cargado.", eventAir: "Sensores de aire seleccionados.", eventCleared: "Alertas resueltas eliminadas.", morning: "Mañana", evening: "Tarde", now: "Ahora" } },
  morph: { title: "Configurador de materiales", kind: "Configurador cinematográfico 3D", prompt: "Diseña un configurador automotriz cinematográfico con controles de materiales, cabina, ruedas, luces y cámara.", capability: "Escenario de producto, materiales, especificaciones, cámara, iluminación y configuración guardada.", proof: "Vista previa en vivo · 14 controles locales · producto CSS/SVG sin fotos stock", ui: { eyebrow: "CONFIGURADOR DE PRODUCTO FÍSICO", configurator: "M-01 / SERIE", model: "MODELO", material: "MATERIAL", cabin: "CABINA", stance: "POSTURA", studio: "Estudio", road: "Carretera", detail: "Detalle", lights: "Luces", rotate: "Girar vista", save: "Guardar especificación", saved: "Especificación guardada localmente para esta demo.", reset: "Restablecer", graphite: "Grafito", pearl: "Perla", copper: "Cobre", cobalt: "Cobalto", wheelAero: "Aero 21", wheelTrack: "Track 22", interiorStone: "Piedra", interiorInk: "Tinta", interiorSaddle: "Cuero", power: "Potencia", range: "Autonomía", sprint: "0–100 km/h", viewFront: "Frontal", viewSide: "Perfil", viewRear: "Trasera", hotspot: "Abrir detalle de material", selection: "ESPECIFICACIÓN ACTUAL", spec: "M-01 Dual Motor", body: "Carrocería", wheel: "Rueda", interior: "Interior", noticeReset: "Configuración de fábrica restaurada." } },
  "studio-ledger": {
    title: "Centro de control para despachos profesionales",
    kind: "App de gestión para despachos",
    prompt: "Crea un espacio de gestión premium para una asesoría contable o despacho profesional, con clientes, vencimientos, documentos y facturas.",
    capability: "Cartera de clientes, calendario fiscal, cola documental, facturación y agenda operativa diaria.",
    proof: "Vista previa de app en vivo · 12 controles locales · flujo de despacho sin red",
  },
  "pulse-booking": {
    title: "Agenda de citas y capacidad",
    kind: "App de reservas y operaciones",
    prompt: "Crea una agenda de citas cuidada para clínicas, salones o estudios profesionales, con calendario, equipo y recorridos de cliente.",
    capability: "Calendario interactivo, disponibilidad del equipo, filtros de servicio, detalle de citas y lista de espera.",
    proof: "Vista previa de app en vivo · 11 controles locales · reservas en memoria",
  },
  "foundry-erp": {
    title: "Sistema operativo empresarial",
    kind: "ERP y software de gestión",
    prompt: "Diseña un sistema de gestión avanzado para pedidos, inventario, clientes, facturas y rendimiento operativo.",
    capability: "Flujo de pedidos, salud del stock, CRM, estado de facturas, alertas e indicadores operativos.",
    proof: "Vista previa de app en vivo · 13 controles locales · simulación ERP sin red",
  },
  "mercedes-epoque": {
    title: "Alquiler de Mercedes clásicos y modernos",
    kind: "Sitio de colección automóvil",
    prompt: "Crea Mercedes Époque, un sitio de alquiler de Mercedes clásicos y modernos, con filtros de época, búsqueda y solicitud de disponibilidad demo.",
    capability: "Filtros de época, colección buscable, ficha del coche, duración y reserva demo.",
    proof: "Vista previa del sitio en vivo · 11 controles locales · fotografía de museo, reserva demo",
  },
  italvia: {
    title: "Concierge inmobiliario Italia–Polonia",
    kind: "Sitio concierge inmobiliario",
    prompt: "Crea Italvia, un concierge inmobiliario Italia–Polonia con honestidad estacional, coste total, dossier de seguridad y agente personal.",
    capability: "Vista verano/invierno, casas curadas, coste total, dossier y mensaje al agente.",
    proof: "Vista previa del sitio en vivo · 10 controles locales · carreteras italianas, concierge sin red",
  },
  "mini4wd-lab": {
    title: "Construye, corta el carbono, pruébalo en pista",
    kind: "Sitio-taller hobby",
    prompt: "Crea Mini4WD Lab, una guía para montar una Mini 4WD, cortar carbono y lanzarla en el salto.",
    capability: "Objetivos, piezas de setup, pasos de carbono y prueba de salto en memoria.",
    proof: "Vista previa del sitio en vivo · 12 controles locales · pista neón fotográfica, taller sin red",
  },
  "atelier-nova": {
    title: "Portfolio de arquitectura y diseño",
    kind: "Sitio para estudio creativo",
    prompt: "Crea un sitio editorial para un estudio de arquitectura e interiorismo con proyectos, método, revista y solicitud de consulta.",
    capability: "Portfolio inmersivo, filtros de proyectos, narrativa editorial y solicitud de consulta.",
    proof: "Vista previa del sitio en vivo · 10 controles locales · imágenes arquitectónicas con CSS",
  },
  "casa-verde": {
    title: "Hospitalidad pausada en la naturaleza",
    kind: "Sitio de hospitalidad",
    prompt: "Crea un sitio evocador para un retiro rural con habitaciones, cocina, experiencias y solicitud de disponibilidad.",
    capability: "Relato de habitaciones, configuración de estancia, experiencias, gastronomía y consulta de reserva.",
    proof: "Vista previa del sitio en vivo · 11 controles locales · reserva de demostración transparente",
  },
  "lumen-clinic": {
    title: "Clínica privada y recorridos asistenciales",
    kind: "Sitio de servicios sanitarios",
    prompt: "Diseña un sitio sereno para una clínica privada que explique especialidades, profesionales, recorridos y solicitud de cita.",
    capability: "Navegación por especialidades, perfiles médicos, recorridos, accesibilidad y solicitud de cita.",
    proof: "Vista previa del sitio en vivo · 12 controles locales · demostración médica solo informativa",
  },
  "northstar-legal": {
    title: "Firma jurídica y asesoría profesional",
    kind: "Sitio para profesionales",
    prompt: "Crea un sitio fiable para una firma jurídica y de asesoría con áreas de práctica, equipo, análisis y contacto confidencial.",
    capability: "Áreas de práctica, perfiles de socios, filtros de análisis, oficinas y consulta confidencial.",
    proof: "Vista previa del sitio en vivo · 10 controles locales · contacto de demostración respetuoso con la privacidad",
  },
  "velora-commerce": {
    title: "Colección de producto prémium",
    kind: "Sitio de comercio electrónico",
    prompt: "Crea un comercio electrónico refinado con colecciones, materiales, configuración de producto y carrito de demostración.",
    capability: "Filtros de colección, relato de producto, elección de color, cantidad, carrito y cálculo de envío.",
    proof: "Vista previa del sitio en vivo · 13 controles locales · carrito simulado sin pago",
  },
  "festival-onda": {
    title: "Cultura y programa en vivo",
    kind: "Sitio para festivales y eventos",
    prompt: "Crea un sitio cultural audaz con programa, escenarios, artistas, agenda personal e información de entradas.",
    capability: "Filtros de programa, mapa de escenarios, fichas de artistas, agenda personal e información de entradas.",
    proof: "Vista previa del sitio en vivo · 12 controles locales · agenda del festival sin red",
  },
});

const fr = translated(en, {
  "orbit-command": { title: "Contrôle de mission orbitale", kind: "Jumeau de systèmes spatiaux", prompt: "Créez un jumeau numérique de contrôle de mission pour une petite flotte de satellites, avec planification orbitale et télémétrie en direct.", capability: "Télémétrie spatiale, sélection de flotte, couches, chronologie et planification de manœuvre.", proof: "Aperçu en direct · 12 contrôles locaux · télémétrie canvas hors ligne", ui: { eyebrow: "CONTRÔLE DE MISSION / ORBITE BASSE", live: "LIAISON ACTIVE", missionTime: "TEMPS MISSION", fleet: "FLOTTE", telemetry: "TÉLÉMÉTRIE", timeline: "CHRONOLOGIE ORBITALE", pause: "Pause", resume: "Reprendre", ground: "Trace au sol", debris: "Champ de débris", paths: "Orbites", zoomIn: "Agrandir", zoomOut: "Réduire", plan: "Planifier la poussée", commit: "Confirmer la manœuvre", cancel: "Annuler le plan", nominal: "Nominal", contact: "Prochain contact", fuel: "Carburant", inclination: "Inclinaison", altitude: "Altitude", selected: "Véhicule sélectionné", noticePlan: "Corridor de manœuvre tracé.", noticeCommitted: "Simulation mise à jour; aucune commande envoyée.", noticeCancelled: "Plan de manœuvre effacé.", station: "Station sol de Kiruna" } },
  neura: { title: "Observatoire des systèmes neuronaux", kind: "Démo de visualisation biotech", prompt: "Créez un démonstrateur non clinique de jumeau neuronal pour explorer régions, signaux et cohortes simulées.", capability: "Visualisation scientifique, comparaison régionale, chronologie des signaux, annotations et captures.", proof: "Aperçu en direct · 10 contrôles locaux · simulation explicitement non clinique", ui: { eyebrow: "OBSERVATOIRE DES SYSTÈMES NEURONAUX", demoNotice: "DÉMO DE RECHERCHE · PAS D’USAGE CLINIQUE", study: "Étude N-204", overview: "Vue d’ensemble", signals: "Signaux", cohort: "Cohorte", compare: "Comparer", region: "RÉGION", cortex: "Cortex", stem: "Tronc cérébral", network: "Réseau", baseline: "Référence", stimulus: "Stimulus", recovery: "Récupération", play: "Lancer la simulation", pause: "Pause", snapshot: "Capturer", annotate: "Ajouter une annotation", reset: "Réinitialiser l’étude", biomarkers: "MARQUEURS SIMULÉS", coherence: "Cohérence", response: "Réponse", symmetry: "Symétrie", activity: "ACTIVITÉ RÉGIONALE", stable: "Motif simulé stable", noteSnapshot: "Capture ajoutée au journal de l’étude.", noteAnnotation: "Annotation ancrée sur l’échantillon actuel.", noteReset: "Vue restaurée à la référence.", timeline: "CHRONOLOGIE DES ÉCHANTILLONS", sample: "Échantillon" } },
  synapse: { title: "Espace d’intelligence collaborative", kind: "Workspace de collaboration IA", prompt: "Concevez un canvas collaboratif premium reliant recherche, décisions, tâches et activité des agents.", capability: "Canvas de connaissances, nœuds typés, recherche, filtres, activité et relations modifiables.", proof: "Aperçu en direct · 11 contrôles locaux · workspace modifiable en mémoire", ui: { eyebrow: "INTELLIGENCE COLLABORATIVE", workspace: "Workspace de lancement Helios", canvas: "Canvas", documents: "Documents", activity: "Activité", search: "Rechercher dans le workspace", addNode: "Nouveau nœud", focus: "Focus", align: "Aligner", connect: "Relier", filterAll: "Tout", filterDecision: "Décisions", filterTask: "Tâches", brief: "Brief de lancement", research: "Recherche audience", direction: "Direction produit", prototype: "Revue prototype", decision: "Décision", task: "Tâche", note: "Note", owner: "Responsable", due: "Échéance", newNode: "Une nouvelle tâche a été ajoutée au canvas.", connected: "Les idées sélectionnées sont maintenant reliées.", aligned: "Les nœuds visibles sont alignés sur la grille.", focused: "Le mode focus isole le fil sélectionné.", searchResult: "éléments correspondants", activityOn: "Panneau d’activité ouvert.", activityOff: "Panneau d’activité fermé." } },
  vanta: { title: "Terminal de risque de marché", kind: "Poste de trading simulé", prompt: "Créez un terminal professionnel dense avec graphiques, watchlist, contrôles de risque et ordres simulés.", capability: "Graphique dynamique, watchlist, profondeur, positions, limites de risque et ordres papier.", proof: "Aperçu en direct · 13 contrôles locaux · trading entièrement simulé", ui: { eyebrow: "TERMINAL DE RISQUE DE MARCHÉ", simulated: "DONNÉES SIMULÉES · AUCUNE EXÉCUTION", markets: "MARCHÉS", blotter: "REGISTRE", risk: "RISQUE", watchlist: "WATCHLIST", symbol: "SYMBOLE", last: "DERNIER", change: "VARIATION", candles: "Bougies", depth: "Profondeur", positions: "POSITIONS", orders: "ORDRES", buy: "ACHETER", sell: "VENDRE", quantity: "Quantité", limit: "Prix limite", simulate: "Simuler l’ordre", cancel: "Annuler en attente", exposure: "EXPOSITION NETTE", var: "VaR SIMULÉE", pnl: "P&L PAPIER", orderReady: "Ticket prêt pour la simulation papier.", orderSent: "Ordre papier ajouté; rien n’a été transmis.", orderCancelled: "Ordre papier en attente annulé.", chart: "PRIX / VOLUME", book: "CARNET D’ORDRES", desk: "EUROPE / GROWTH DESK" } },
  "arc-city": { title: "Jumeau des systèmes urbains", kind: "Jumeau numérique urbain", prompt: "Créez un jumeau urbain centré sur la carte pour explorer trafic, énergie et environnement par quartier et dans le temps.", capability: "Carte urbaine multicouche, inspection des quartiers, simulation temporelle, alertes et métriques.", proof: "Aperçu en direct · 12 contrôles locaux · modèle urbain SVG hors ligne", ui: { eyebrow: "JUMEAU DES SYSTÈMES URBAINS", layers: "COUCHES", traffic: "Trafic", energy: "Énergie", air: "Qualité de l’air", water: "Eau", transit: "Transport", districts: "QUARTIERS", harbor: "Port", central: "Centre", north: "Réseau nord", timeline: "CHRONOLOGIE DE LA VILLE", live: "Direct", simulate: "Simuler le soir", pause: "Pause", resume: "Reprendre", zoomIn: "Agrandir", zoomOut: "Réduire", alerts: "ALERTES", clear: "Effacer résolues", camera: "Recentrer la carte", inspect: "Inspecter le quartier", demand: "Demande énergétique", flow: "Flux du trafic", quality: "Indice de l’air", occupancy: "Charge du transport", selected: "Quartier sélectionné", eventTraffic: "Couche trafic mise en évidence.", eventEnergy: "Scénario de demande du soir chargé.", eventAir: "Capteurs de qualité de l’air sélectionnés.", eventCleared: "Alertes résolues supprimées.", morning: "Matin", evening: "Soir", now: "Maintenant" } },
  morph: { title: "Configurateur de matériaux", kind: "Configurateur cinématique 3D", prompt: "Concevez un configurateur automobile cinématique avec contrôles de matériaux, habitacle, roues, lumière et caméra.", capability: "Scène produit, matériaux, spécifications, rotation caméra, éclairage et configuration enregistrée.", proof: "Aperçu en direct · 14 contrôles locaux · produit CSS/SVG sans photo stock", ui: { eyebrow: "CONFIGURATEUR DE PRODUIT PHYSIQUE", configurator: "M-01 / SÉRIE", model: "MODÈLE", material: "MATÉRIAU", cabin: "HABITACLE", stance: "ASSIETTE", studio: "Studio", road: "Route", detail: "Détail", lights: "Lumières", rotate: "Faire pivoter", save: "Enregistrer la spécification", saved: "Spécification enregistrée localement pour cette démo.", reset: "Réinitialiser", graphite: "Graphite", pearl: "Perle", copper: "Cuivre", cobalt: "Cobalt", wheelAero: "Aero 21", wheelTrack: "Track 22", interiorStone: "Pierre", interiorInk: "Encre", interiorSaddle: "Cuir", power: "Puissance", range: "Autonomie", sprint: "0–100 km/h", viewFront: "Avant", viewSide: "Profil", viewRear: "Arrière", hotspot: "Ouvrir le détail du matériau", selection: "SPÉCIFICATION ACTUELLE", spec: "M-01 Dual Motor", body: "Carrosserie", wheel: "Roue", interior: "Intérieur", noticeReset: "Configuration d’usine restaurée." } },
  "studio-ledger": {
    title: "Poste de pilotage pour cabinets professionnels",
    kind: "Application de gestion de cabinet",
    prompt: "Créez un espace de gestion haut de gamme pour un cabinet comptable ou professionnel, avec clients, échéances, documents et factures.",
    capability: "Portefeuille clients, calendrier fiscal, file documentaire, facturation et programme de travail quotidien.",
    proof: "Aperçu d’application en direct · 12 contrôles locaux · flux cabinet hors ligne",
  },
  "pulse-booking": {
    title: "Agenda de rendez-vous et capacité",
    kind: "Application de réservation opérationnelle",
    prompt: "Créez un agenda de rendez-vous soigné pour une clinique, un salon ou un cabinet, avec calendrier, équipe et parcours client.",
    capability: "Calendrier interactif, disponibilité de l’équipe, filtres de service, détail des rendez-vous et liste d’attente.",
    proof: "Aperçu d’application en direct · 11 contrôles locaux · réservations en mémoire",
  },
  "foundry-erp": {
    title: "Système d’exploitation de l’entreprise",
    kind: "ERP et logiciel de gestion",
    prompt: "Concevez un système de gestion haut de gamme pour les commandes, les stocks, les clients, les factures et la performance opérationnelle.",
    capability: "Pipeline de commandes, santé des stocks, CRM, état des factures, alertes et indicateurs opérationnels.",
    proof: "Aperçu d’application en direct · 13 contrôles locaux · simulation ERP hors ligne",
  },
  "mercedes-epoque": {
    title: "Location de Mercedes classiques et modernes",
    kind: "Site de collection automobile",
    prompt: "Créez Mercedes Époque, un site de location de Mercedes classiques et modernes, avec filtres d’époque, recherche et demande de disponibilité démo.",
    capability: "Filtres d’époque, collection searchable, fiche voiture, durée et réservation démo.",
    proof: "Aperçu du site en direct · 11 contrôles locaux · photographie muséale, réservation démo",
  },
  italvia: {
    title: "Conciergerie immobilière Italie–Pologne",
    kind: "Site concierge immobilier",
    prompt: "Créez Italvia, une conciergerie immobilière Italie–Pologne avec honnêteté saisonnière, coût global, dossier de sécurité et agente personnelle.",
    capability: "Vue été/hiver, maisons choisies, coût global, dossier et message à l’agente.",
    proof: "Aperçu du site en direct · 10 contrôles locaux · routes italiennes photographiées, concierge hors ligne",
  },
  "mini4wd-lab": {
    title: "Construire, couper le carbone, tester en piste",
    kind: "Site-atelier hobby",
    prompt: "Créez Mini4WD Lab, un guide pour monter une Mini 4WD, couper le carbone et la lancer sur le saut.",
    capability: "Objectifs, pièces de setup, étapes carbone et test de saut en mémoire.",
    proof: "Aperçu du site en direct · 12 contrôles locaux · piste néon photographiée, atelier hors ligne",
  },
  "atelier-nova": {
    title: "Portfolio d’architecture et de design",
    kind: "Site de studio créatif",
    prompt: "Créez un site éditorial pour un studio d’architecture et de design intérieur, avec projets, méthode, journal et demande de consultation.",
    capability: "Portfolio immersif, filtres de projets, narration éditoriale et demande de consultation.",
    proof: "Aperçu du site en direct · 10 contrôles locaux · visuels architecturaux créés en CSS",
  },
  "casa-verde": {
    title: "Hospitalité lente au cœur de la nature",
    kind: "Site d’hospitalité",
    prompt: "Créez un site évocateur pour une retraite à la campagne, avec chambres, cuisine, expériences et demande de disponibilité.",
    capability: "Présentation des chambres, configuration du séjour, expériences, restauration et demande de réservation.",
    proof: "Aperçu du site en direct · 11 contrôles locaux · réservation de démonstration transparente",
  },
  "lumen-clinic": {
    title: "Clinique privée et parcours de soins",
    kind: "Site de services de santé",
    prompt: "Concevez un site rassurant pour une clinique privée qui présente spécialités, médecins, parcours et demande de rendez-vous.",
    capability: "Navigation par spécialité, profils médicaux, parcours, accessibilité et demande de rendez-vous.",
    proof: "Aperçu du site en direct · 12 contrôles locaux · démonstration médicale strictement informative",
  },
  "northstar-legal": {
    title: "Cabinet juridique et conseil professionnel",
    kind: "Site pour professionnels",
    prompt: "Créez un site de confiance pour un cabinet juridique et de conseil, avec expertises, équipe, analyses et prise de contact confidentielle.",
    capability: "Domaines d’expertise, profils des associés, filtres d’analyses, bureaux et demande confidentielle.",
    proof: "Aperçu du site en direct · 10 contrôles locaux · contact de démonstration respectueux de la vie privée",
  },
  "velora-commerce": {
    title: "Collection de produits haut de gamme",
    kind: "Site de commerce en ligne",
    prompt: "Créez un site marchand raffiné avec collections, matières, configuration produit et panier de démonstration.",
    capability: "Filtres de collection, histoire du produit, choix de couleur, quantité, panier et estimation de livraison.",
    proof: "Aperçu du site en direct · 13 contrôles locaux · panier simulé sans paiement",
  },
  "festival-onda": {
    title: "Culture et programme en direct",
    kind: "Site de festival et d’événements",
    prompt: "Créez un site culturel audacieux avec programme, scènes, artistes, agenda personnel et informations billetterie.",
    capability: "Filtres du programme, plan des scènes, fiches artistes, agenda personnel et informations billetterie.",
    proof: "Aperçu du site en direct · 12 contrôles locaux · agenda du festival hors ligne",
  },
});

const de = translated(en, {
  "orbit-command": { title: "Orbitale Missionskontrolle", kind: "Digitaler Zwilling für Raumfahrtsysteme", prompt: "Erstelle einen Missionskontroll-Zwilling für eine kleine Satellitenflotte mit Bahnplanung und Live-Telemetrie.", capability: "Räumliche Telemetrie, Flottenauswahl, Ebenen, Zeitleiste und Manöverplanung.", proof: "Live-App-Vorschau · 12 lokale Steuerungen · Offline-Canvas-Telemetrie", ui: { eyebrow: "MISSIONSKONTROLLE / NIEDRIGE UMLAUFBAHN", live: "LIVE-VERBINDUNG", missionTime: "MISSIONSZEIT", fleet: "FLOTTE", telemetry: "TELEMETRIE", timeline: "ORBIT-ZEITLEISTE", pause: "Pause", resume: "Fortsetzen", ground: "Bodenspur", debris: "Trümmerfeld", paths: "Umlaufbahnen", zoomIn: "Vergrößern", zoomOut: "Verkleinern", plan: "Zündung planen", commit: "Manöver bestätigen", cancel: "Plan verwerfen", nominal: "Nominal", contact: "Nächster Kontakt", fuel: "Treibstoff", inclination: "Neigung", altitude: "Höhe", selected: "Ausgewähltes Fahrzeug", noticePlan: "Manöverkorridor geplant.", noticeCommitted: "Simulation aktualisiert; kein Befehl gesendet.", noticeCancelled: "Manöverplan gelöscht.", station: "Bodenstation Kiruna" } },
  neura: { title: "Observatorium neuronaler Systeme", kind: "Biotech-Visualisierungsdemo", prompt: "Erstelle einen nichtklinischen neuronalen Zwilling zur Erkundung simulierter Regionen, Signale und Kohorten.", capability: "Wissenschaftliche Visualisierung, Regionsvergleich, Signalzeitleiste, Anmerkungen und Momentaufnahmen.", proof: "Live-App-Vorschau · 10 lokale Steuerungen · ausdrücklich nichtklinische Simulation", ui: { eyebrow: "OBSERVATORIUM NEURONALER SYSTEME", demoNotice: "FORSCHUNGSDEMO · NICHT FÜR KLINISCHE NUTZUNG", study: "Studie N-204", overview: "Übersicht", signals: "Signale", cohort: "Kohorte", compare: "Vergleichen", region: "REGION", cortex: "Kortex", stem: "Hirnstamm", network: "Netzwerk", baseline: "Basis", stimulus: "Stimulus", recovery: "Erholung", play: "Simulation starten", pause: "Pause", snapshot: "Momentaufnahme", annotate: "Anmerkung hinzufügen", reset: "Studie zurücksetzen", biomarkers: "SIMULIERTE MARKER", coherence: "Kohärenz", response: "Reaktion", symmetry: "Symmetrie", activity: "REGIONALE AKTIVITÄT", stable: "Stabiles simuliertes Muster", noteSnapshot: "Momentaufnahme zum Studienprotokoll hinzugefügt.", noteAnnotation: "Anmerkung an aktueller Probe verankert.", noteReset: "Studienansicht auf Basis zurückgesetzt.", timeline: "PROBEN-ZEITLEISTE", sample: "Probe" } },
  synapse: { title: "Arbeitsraum für kollaborative Intelligenz", kind: "KI-Kollaborationsworkspace", prompt: "Entwirf eine hochwertige kollaborative Fläche für Forschung, Entscheidungen, Aufgaben und Agentenaktivität.", capability: "Wissensfläche, typisierte Knoten, Suche, Filter, Aktivität und bearbeitbare Beziehungen.", proof: "Live-App-Vorschau · 11 lokale Steuerungen · editierbarer In-Memory-Workspace", ui: { eyebrow: "KOLLABORATIVE INTELLIGENZ", workspace: "Helios Launch-Workspace", canvas: "Canvas", documents: "Dokumente", activity: "Aktivität", search: "Workspace durchsuchen", addNode: "Neuer Knoten", focus: "Fokus", align: "Ausrichten", connect: "Verbinden", filterAll: "Alle", filterDecision: "Entscheidungen", filterTask: "Aufgaben", brief: "Launch-Briefing", research: "Zielgruppenforschung", direction: "Produktrichtung", prototype: "Prototyp-Review", decision: "Entscheidung", task: "Aufgabe", note: "Notiz", owner: "Verantwortlich", due: "Fällig", newNode: "Eine neue Aufgabe wurde zur Fläche hinzugefügt.", connected: "Ausgewählte Ideen sind jetzt verbunden.", aligned: "Sichtbare Knoten am Raster ausgerichtet.", focused: "Fokusmodus isoliert den ausgewählten Strang.", searchResult: "passende Workspace-Elemente", activityOn: "Aktivitätsbereich geöffnet.", activityOff: "Aktivitätsbereich geschlossen." } },
  vanta: { title: "Marktrisiko-Terminal", kind: "Simulierter Trading-Arbeitsplatz", prompt: "Erstelle ein dichtes professionelles Marktterminal mit Charts, Watchlist, Risikokontrollen und simulierten Orders.", capability: "Dynamischer Chart, Watchlist, Markttiefe, Positionen, Risikolimits und Paper-Order-Workflow.", proof: "Live-App-Vorschau · 13 lokale Steuerungen · vollständig simulierter Handel", ui: { eyebrow: "MARKTRISIKO-TERMINAL", simulated: "SIMULIERTE DATEN · KEINE AUSFÜHRUNG", markets: "MÄRKTE", blotter: "ORDERBUCH", risk: "RISIKO", watchlist: "WATCHLIST", symbol: "SYMBOL", last: "LETZTER", change: "ÄNDERUNG", candles: "Kerzen", depth: "Tiefe", positions: "POSITIONEN", orders: "ORDERS", buy: "KAUFEN", sell: "VERKAUFEN", quantity: "Menge", limit: "Limitpreis", simulate: "Order simulieren", cancel: "Offene stornieren", exposure: "NETTOEXPOSURE", var: "SIMULIERTER VaR", pnl: "PAPER P&L", orderReady: "Orderticket bereit für die Paper-Simulation.", orderSent: "Paper-Order hinzugefügt; nichts wurde übertragen.", orderCancelled: "Offene Paper-Order storniert.", chart: "PREIS / VOLUMEN", book: "ORDERBUCH", desk: "EUROPA / GROWTH DESK" } },
  "arc-city": { title: "Zwilling urbaner Systeme", kind: "Smart-City-Zwilling", prompt: "Erstelle einen kartenorientierten Stadtzwilling für Verkehr, Energie und Umwelt über Bezirke und Zeit.", capability: "Mehrschichtige Stadtkarte, Bezirksinspektion, Zeitsimulation, Warnungen und Infrastrukturmetriken.", proof: "Live-App-Vorschau · 12 lokale Steuerungen · Offline-SVG-Stadtmodell", ui: { eyebrow: "ZWILLING URBANER SYSTEME", layers: "EBENEN", traffic: "Verkehr", energy: "Energie", air: "Luftqualität", water: "Wasser", transit: "ÖPNV", districts: "BEZIRKE", harbor: "Hafen", central: "Zentrum", north: "Nordnetz", timeline: "STADT-ZEITLEISTE", live: "Live", simulate: "Abend simulieren", pause: "Pause", resume: "Fortsetzen", zoomIn: "Vergrößern", zoomOut: "Verkleinern", alerts: "WARNUNGEN", clear: "Gelöste entfernen", camera: "Karte zentrieren", inspect: "Bezirk untersuchen", demand: "Energiebedarf", flow: "Verkehrsfluss", quality: "Luftindex", occupancy: "ÖPNV-Auslastung", selected: "Ausgewählter Bezirk", eventTraffic: "Verkehrsebene hervorgehoben.", eventEnergy: "Abendliches Bedarfsszenario geladen.", eventAir: "Luftsensoren ausgewählt.", eventCleared: "Gelöste Warnungen entfernt.", morning: "Morgen", evening: "Abend", now: "Jetzt" } },
  morph: { title: "Materialkonfigurator", kind: "Filmischer 3D-Konfigurator", prompt: "Entwirf einen filmischen Fahrzeugkonfigurator mit Material-, Innenraum-, Rad-, Licht- und Kamerasteuerung.", capability: "Produktbühne, Materialien, Spezifikationen, Kameradrehung, Beleuchtung und gespeicherte Konfiguration.", proof: "Live-App-Vorschau · 14 lokale Steuerungen · CSS/SVG-Produkt ohne Stockfoto", ui: { eyebrow: "KONFIGURATOR FÜR PHYSISCHE PRODUKTE", configurator: "M-01 / SERIE", model: "MODELL", material: "MATERIAL", cabin: "INNENRAUM", stance: "HALTUNG", studio: "Studio", road: "Straße", detail: "Detail", lights: "Lichter", rotate: "Ansicht drehen", save: "Spezifikation speichern", saved: "Spezifikation lokal für diese Demo gespeichert.", reset: "Zurücksetzen", graphite: "Graphit", pearl: "Perle", copper: "Kupfer", cobalt: "Kobalt", wheelAero: "Aero 21", wheelTrack: "Track 22", interiorStone: "Stein", interiorInk: "Tinte", interiorSaddle: "Sattel", power: "Leistung", range: "Reichweite", sprint: "0–100 km/h", viewFront: "Front", viewSide: "Profil", viewRear: "Heck", hotspot: "Materialdetail öffnen", selection: "AKTUELLE SPEZIFIKATION", spec: "M-01 Dual Motor", body: "Karosserie", wheel: "Rad", interior: "Innenraum", noticeReset: "Werkskonfiguration wiederhergestellt." } },
  "studio-ledger": {
    title: "Leitstand für Kanzleien und Praxen",
    kind: "Praxis- und Kanzleiverwaltung",
    prompt: "Erstelle einen hochwertigen Verwaltungsbereich für eine Steuerkanzlei oder professionelle Praxis mit Mandanten, Fristen, Dokumenten und Rechnungen.",
    capability: "Mandantenportfolio, Fristenkalender, Dokumentenablage, Honorarübersicht und tägliche Arbeitsliste.",
    proof: "Live-App-Vorschau · 12 lokale Steuerungen · Offline-Kanzleiablauf",
  },
  "pulse-booking": {
    title: "Termin- und Kapazitätsplanung",
    kind: "Buchungs- und Betriebsanwendung",
    prompt: "Erstelle einen eleganten Terminplaner für Klinik, Salon oder Praxis mit Kalender, Team und Kundenabläufen.",
    capability: "Interaktiver Kalender, Teamverfügbarkeit, Leistungsfilter, Termindetails und Warteliste.",
    proof: "Live-App-Vorschau · 11 lokale Steuerungen · Buchungen im Arbeitsspeicher",
  },
  "foundry-erp": {
    title: "Betriebssystem für Unternehmen",
    kind: "ERP und Verwaltungssoftware",
    prompt: "Entwirf ein hochwertiges Verwaltungssystem für Aufträge, Lager, Kunden, Rechnungen und operative Leistung.",
    capability: "Auftragspipeline, Lagerzustand, CRM, Rechnungsstatus, Warnungen und Betriebskennzahlen.",
    proof: "Live-App-Vorschau · 13 lokale Steuerungen · Offline-ERP-Simulation",
  },
  "mercedes-epoque": {
    title: "Miete klassischer und moderner Mercedes",
    kind: "Website für Autokollektion",
    prompt: "Baue Mercedes Époque, eine Mietseite für klassische und moderne Mercedes mit Epochenfiltern, Suche und Demo-Verfügbarkeit.",
    capability: "Epochenfilter, durchsuchbare Sammlung, Autodetails, Dauer und Demo-Reservierung.",
    proof: "Live-Website-Vorschau · 11 lokale Steuerungen · Museumfotografie, Demo-Reservierung",
  },
  italvia: {
    title: "Immobilien-Concierge Italien–Polen",
    kind: "Immobilien-Concierge-Website",
    prompt: "Baue Italvia, einen Immobilien-Concierge Italien–Polen mit jahreszeitlicher Ehrlichkeit, Gesamtkosten, Sicherheitsdossier und persönlicher Agentin.",
    capability: "Sommer/Winter-Ansicht, kuratierte Häuser, Gesamtkosten, Dossier und Nachricht an die Agentin.",
    proof: "Live-Website-Vorschau · 10 lokale Steuerungen · italienische Straßenfotografie, Offline-Concierge",
  },
  "mini4wd-lab": {
    title: "Bauen, Carbon schneiden, auf der Bahn testen",
    kind: "Hobby-Werkstatt-Website",
    prompt: "Baue Mini4WD Lab, eine Anleitung zum Zusammenbauen einer Mini 4WD, Carbon schneiden und auf den Sprung schicken.",
    capability: "Ziele, Setup-Teile, Carbon-Schritte und Sprungtest im Speicher.",
    proof: "Live-Website-Vorschau · 12 lokale Steuerungen · Neon-Bahn-Fotografie, Offline-Werkstatt",
  },
  "atelier-nova": {
    title: "Portfolio für Architektur und Design",
    kind: "Website für ein Kreativstudio",
    prompt: "Erstelle eine redaktionelle Website für ein Architektur- und Interior-Design-Studio mit Projekten, Arbeitsweise, Journal und Beratungsanfrage.",
    capability: "Immersives Portfolio, Projektfilter, redaktionelles Storytelling und Beratungsanfrage.",
    proof: "Live-Website-Vorschau · 10 lokale Steuerungen · Architekturbilder aus CSS",
  },
  "casa-verde": {
    title: "Entschleunigte Gastlichkeit in der Natur",
    kind: "Website für Gastgewerbe",
    prompt: "Erstelle eine stimmungsvolle Website für einen Rückzugsort auf dem Land mit Zimmern, Küche, Erlebnissen und Verfügbarkeitsanfrage.",
    capability: "Zimmergeschichten, Aufenthaltskonfiguration, Erlebnisse, Gastronomie und Buchungsanfrage.",
    proof: "Live-Website-Vorschau · 11 lokale Steuerungen · transparente Demo-Buchung",
  },
  "lumen-clinic": {
    title: "Privatklinik und Behandlungspfade",
    kind: "Website für Gesundheitsleistungen",
    prompt: "Entwirf eine ruhige Website für eine Privatklinik, die Fachgebiete, Ärzte, Behandlungspfade und Terminanfragen klar erklärt.",
    capability: "Fachgebietsnavigation, Arztprofile, Behandlungspfade, Barrierefreiheit und Terminanfrage.",
    proof: "Live-Website-Vorschau · 12 lokale Steuerungen · ausdrücklich nur informative Medizin-Demo",
  },
  "northstar-legal": {
    title: "Kanzlei und professionelle Beratung",
    kind: "Website für professionelle Dienste",
    prompt: "Erstelle eine vertrauenswürdige Website für eine Rechts- und Beratungskanzlei mit Fachgebieten, Team, Einblicken und vertraulicher Anfrage.",
    capability: "Rechtsgebiete, Partnerprofile, Einblicksfilter, Standorte und vertrauliche Anfrage.",
    proof: "Live-Website-Vorschau · 10 lokale Steuerungen · datenschutzbewusste Demo-Anfrage",
  },
  "velora-commerce": {
    title: "Hochwertige Produktkollektion",
    kind: "E-Commerce-Website",
    prompt: "Erstelle eine elegante E-Commerce-Website mit Kollektionen, Materialgeschichten, Produktkonfiguration und Demo-Warenkorb.",
    capability: "Kollektionsfilter, Produktgeschichte, Farbauswahl, Menge, Warenkorb und Versandkostenschätzung.",
    proof: "Live-Website-Vorschau · 13 lokale Steuerungen · simulierter Warenkorb ohne Bezahlung",
  },
  "festival-onda": {
    title: "Kultur und Live-Programm",
    kind: "Website für Festivals und Events",
    prompt: "Erstelle eine mutige Kulturfestival-Website mit Programm, Bühnen, Künstlern, persönlichem Zeitplan und Ticketinformationen.",
    capability: "Programmfilter, Bühnenplan, Künstlerkarten, persönlicher Zeitplan und Ticketinformationen.",
    proof: "Live-Website-Vorschau · 12 lokale Steuerungen · Offline-Festivalplaner",
  },
});

const pt = translated(en, {
  "orbit-command": { title: "Controle de missão orbital", kind: "Gêmeo de sistemas espaciais", prompt: "Crie um gêmeo digital de controle de missão para uma pequena frota de satélites, com planejamento orbital e telemetria ao vivo.", capability: "Telemetria espacial, seleção de frota, camadas, linha do tempo e planejamento de manobras.", proof: "Prévia ao vivo · 12 controles locais · telemetria canvas offline", ui: { eyebrow: "CONTROLE DE MISSÃO / ÓRBITA BAIXA", live: "LINK ATIVO", missionTime: "TEMPO DE MISSÃO", fleet: "FROTA", telemetry: "TELEMETRIA", timeline: "LINHA ORBITAL", pause: "Pausar", resume: "Retomar", ground: "Trajeto terrestre", debris: "Campo de detritos", paths: "Órbitas", zoomIn: "Ampliar", zoomOut: "Reduzir", plan: "Planejar impulso", commit: "Confirmar manobra", cancel: "Cancelar plano", nominal: "Nominal", contact: "Próximo contato", fuel: "Combustível", inclination: "Inclinação", altitude: "Altitude", selected: "Veículo selecionado", noticePlan: "Corredor de manobra traçado.", noticeCommitted: "Simulação atualizada; nenhum comando foi enviado.", noticeCancelled: "Plano de manobra removido.", station: "Estação terrestre de Kiruna" } },
  neura: { title: "Observatório de sistemas neurais", kind: "Demo de visualização biotech", prompt: "Crie um demonstrador não clínico de gêmeo neural para explorar regiões, sinais e coortes simuladas.", capability: "Visualização científica, comparação regional, linha de sinais, anotações e capturas.", proof: "Prévia ao vivo · 10 controles locais · simulação explicitamente não clínica", ui: { eyebrow: "OBSERVATÓRIO DE SISTEMAS NEURAIS", demoNotice: "DEMO DE PESQUISA · NÃO PARA USO CLÍNICO", study: "Estudo N-204", overview: "Visão geral", signals: "Sinais", cohort: "Coorte", compare: "Comparar", region: "REGIÃO", cortex: "Córtex", stem: "Tronco cerebral", network: "Rede", baseline: "Base", stimulus: "Estímulo", recovery: "Recuperação", play: "Executar simulação", pause: "Pausar", snapshot: "Capturar imagem", annotate: "Adicionar anotação", reset: "Redefinir estudo", biomarkers: "MARCADORES SIMULADOS", coherence: "Coerência", response: "Resposta", symmetry: "Simetria", activity: "ATIVIDADE REGIONAL", stable: "Padrão simulado estável", noteSnapshot: "Captura adicionada ao registro do estudo.", noteAnnotation: "Anotação fixada na amostra atual.", noteReset: "Vista restaurada à linha de base.", timeline: "LINHA DE AMOSTRAS", sample: "Amostra" } },
  synapse: { title: "Espaço de inteligência colaborativa", kind: "Workspace de colaboração IA", prompt: "Projete um canvas colaborativo premium para conectar pesquisa, decisões, tarefas e atividade dos agentes.", capability: "Canvas de conhecimento, nós tipados, busca, filtros, atividade e relações editáveis.", proof: "Prévia ao vivo · 11 controles locais · workspace editável em memória", ui: { eyebrow: "INTELIGÊNCIA COLABORATIVA", workspace: "Workspace de lançamento Helios", canvas: "Canvas", documents: "Documentos", activity: "Atividade", search: "Buscar no workspace", addNode: "Novo nó", focus: "Foco", align: "Alinhar", connect: "Conectar", filterAll: "Tudo", filterDecision: "Decisões", filterTask: "Tarefas", brief: "Brief de lançamento", research: "Pesquisa de público", direction: "Direção do produto", prototype: "Revisão do protótipo", decision: "Decisão", task: "Tarefa", note: "Nota", owner: "Responsável", due: "Prazo", newNode: "Uma nova tarefa foi adicionada ao canvas.", connected: "As ideias selecionadas agora estão conectadas.", aligned: "Nós visíveis alinhados à grade.", focused: "O modo foco isola o fio selecionado.", searchResult: "itens correspondentes", activityOn: "Painel de atividade aberto.", activityOff: "Painel de atividade fechado." } },
  vanta: { title: "Terminal de risco de mercado", kind: "Estação de trading simulada", prompt: "Crie um terminal profissional denso com gráficos, watchlist, controles de risco e ordens simuladas.", capability: "Gráfico dinâmico, watchlist, profundidade, posições, limites de risco e ordens paper.", proof: "Prévia ao vivo · 13 controles locais · trading totalmente simulado", ui: { eyebrow: "TERMINAL DE RISCO DE MERCADO", simulated: "DADOS SIMULADOS · SEM EXECUÇÃO", markets: "MERCADOS", blotter: "REGISTRO", risk: "RISCO", watchlist: "WATCHLIST", symbol: "SÍMBOLO", last: "ÚLTIMO", change: "VARIAÇÃO", candles: "Velas", depth: "Profundidade", positions: "POSIÇÕES", orders: "ORDENS", buy: "COMPRAR", sell: "VENDER", quantity: "Quantidade", limit: "Preço limite", simulate: "Simular ordem", cancel: "Cancelar pendente", exposure: "EXPOSIÇÃO LÍQUIDA", var: "VaR SIMULADO", pnl: "P&L PAPER", orderReady: "Ticket pronto para simulação paper.", orderSent: "Ordem paper adicionada; nada foi transmitido.", orderCancelled: "Ordem paper pendente cancelada.", chart: "PREÇO / VOLUME", book: "LIVRO DE ORDENS", desk: "EUROPA / GROWTH DESK" } },
  "arc-city": { title: "Gêmeo de sistemas urbanos", kind: "Gêmeo digital de cidade", prompt: "Crie um gêmeo urbano centrado no mapa para explorar tráfego, energia e ambiente por distrito e tempo.", capability: "Mapa urbano em camadas, inspeção de distritos, simulação temporal, alertas e métricas.", proof: "Prévia ao vivo · 12 controles locais · modelo urbano SVG offline", ui: { eyebrow: "GÊMEO DE SISTEMAS URBANOS", layers: "CAMADAS", traffic: "Tráfego", energy: "Energia", air: "Qualidade do ar", water: "Água", transit: "Transporte", districts: "DISTRITOS", harbor: "Porto", central: "Centro", north: "Rede norte", timeline: "LINHA DA CIDADE", live: "Ao vivo", simulate: "Simular noite", pause: "Pausar", resume: "Retomar", zoomIn: "Ampliar", zoomOut: "Reduzir", alerts: "ALERTAS", clear: "Limpar resolvidos", camera: "Centralizar mapa", inspect: "Inspecionar distrito", demand: "Demanda de energia", flow: "Fluxo de tráfego", quality: "Índice do ar", occupancy: "Carga do transporte", selected: "Distrito selecionado", eventTraffic: "Camada de tráfego destacada.", eventEnergy: "Cenário de demanda noturna carregado.", eventAir: "Sensores de ar selecionados.", eventCleared: "Alertas resolvidos removidos.", morning: "Manhã", evening: "Noite", now: "Agora" } },
  morph: { title: "Configurador de materiais", kind: "Configurador cinematográfico 3D", prompt: "Projete um configurador automotivo cinematográfico com controles de materiais, cabine, rodas, luzes e câmera.", capability: "Palco de produto, materiais, especificações, câmera, iluminação e configuração salva.", proof: "Prévia ao vivo · 14 controles locais · produto CSS/SVG sem fotos stock", ui: { eyebrow: "CONFIGURADOR DE PRODUTO FÍSICO", configurator: "M-01 / SÉRIE", model: "MODELO", material: "MATERIAL", cabin: "CABINE", stance: "POSTURA", studio: "Estúdio", road: "Estrada", detail: "Detalhe", lights: "Luzes", rotate: "Girar vista", save: "Salvar especificação", saved: "Especificação salva localmente para esta demo.", reset: "Redefinir", graphite: "Grafite", pearl: "Pérola", copper: "Cobre", cobalt: "Cobalto", wheelAero: "Aero 21", wheelTrack: "Track 22", interiorStone: "Pedra", interiorInk: "Tinta", interiorSaddle: "Couro", power: "Potência", range: "Autonomia", sprint: "0–100 km/h", viewFront: "Frente", viewSide: "Perfil", viewRear: "Traseira", hotspot: "Abrir detalhe do material", selection: "ESPECIFICAÇÃO ATUAL", spec: "M-01 Dual Motor", body: "Carroceria", wheel: "Roda", interior: "Interior", noticeReset: "Configuração de fábrica restaurada." } },
  "studio-ledger": {
    title: "Centro de comando para gabinetes profissionais",
    kind: "Aplicação de gestão de gabinete",
    prompt: "Cria um espaço de gestão premium para um gabinete de contabilidade ou profissional, com clientes, prazos, documentos e faturas.",
    capability: "Carteira de clientes, calendário fiscal, fila documental, faturação e agenda operacional diária.",
    proof: "Prévia da aplicação ao vivo · 12 controlos locais · fluxo de gabinete offline",
  },
  "pulse-booking": {
    title: "Agenda de marcações e capacidade",
    kind: "Aplicação de reservas e operações",
    prompt: "Cria uma agenda de marcações cuidada para clínicas, salões ou gabinetes, com calendário, equipa e percursos do cliente.",
    capability: "Calendário interativo, disponibilidade da equipa, filtros de serviço, detalhe de marcações e lista de espera.",
    proof: "Prévia da aplicação ao vivo · 11 controlos locais · reservas em memória",
  },
  "foundry-erp": {
    title: "Sistema operativo empresarial",
    kind: "ERP e software de gestão",
    prompt: "Desenha um sistema de gestão avançado para encomendas, inventário, clientes, faturas e desempenho operacional.",
    capability: "Fluxo de encomendas, estado do stock, CRM, situação das faturas, alertas e indicadores operacionais.",
    proof: "Prévia da aplicação ao vivo · 13 controlos locais · simulação ERP offline",
  },
  "mercedes-epoque": {
    title: "Aluguer de Mercedes clássicos e modernos",
    kind: "Site de coleção automóvel",
    prompt: "Cria Mercedes Époque, um site de aluguer de Mercedes clássicos e modernos, com filtros de época, pesquisa e pedido de disponibilidade demo.",
    capability: "Filtros de época, coleção pesquisável, ficha do carro, duração e reserva demo.",
    proof: "Prévia do site ao vivo · 11 controlos locais · fotografia de museu, reserva demo",
  },
  italvia: {
    title: "Concierge imobiliário Itália–Polónia",
    kind: "Site concierge imobiliário",
    prompt: "Cria Italvia, um concierge imobiliário Itália–Polónia com honestidade sazonal, custo total, dossier de segurança e agente pessoal.",
    capability: "Vista verão/inverno, casas curadas, custo total, dossier e mensagem à agente.",
    proof: "Prévia do site ao vivo · 10 controlos locais · estradas italianas, concierge offline",
  },
  "mini4wd-lab": {
    title: "Constrói, corta o carbono, testa na pista",
    kind: "Site-oficina hobby",
    prompt: "Cria Mini4WD Lab, um guia para montar uma Mini 4WD, cortar carbono e lançá-la no salto.",
    capability: "Objetivos, peças de setup, passos de carbono e teste de salto em memória.",
    proof: "Prévia do site ao vivo · 12 controlos locais · pista néon fotográfica, oficina offline",
  },
  "atelier-nova": {
    title: "Portefólio de arquitetura e design",
    kind: "Site para estúdio criativo",
    prompt: "Cria um site editorial para um estúdio de arquitetura e design de interiores com projetos, método, revista e pedido de consulta.",
    capability: "Portefólio imersivo, filtros de projetos, narrativa editorial e pedido de consulta.",
    proof: "Prévia do site ao vivo · 10 controlos locais · imagens arquitetónicas criadas em CSS",
  },
  "casa-verde": {
    title: "Hospitalidade tranquila na natureza",
    kind: "Site de hospitalidade",
    prompt: "Cria um site atmosférico para um retiro rural com quartos, cozinha, experiências e pedido de disponibilidade.",
    capability: "Histórias dos quartos, configuração da estadia, experiências, restauração e pedido de reserva.",
    proof: "Prévia do site ao vivo · 11 controlos locais · reserva de demonstração transparente",
  },
  "lumen-clinic": {
    title: "Clínica privada e percursos de cuidados",
    kind: "Site de serviços de saúde",
    prompt: "Desenha um site sereno para uma clínica privada que explique especialidades, médicos, percursos e pedidos de marcação.",
    capability: "Navegação por especialidade, perfis médicos, percursos, acessibilidade e pedido de marcação.",
    proof: "Prévia do site ao vivo · 12 controlos locais · demonstração médica apenas informativa",
  },
  "northstar-legal": {
    title: "Sociedade jurídica e consultoria profissional",
    kind: "Site para profissionais",
    prompt: "Cria um site de confiança para uma sociedade jurídica e de consultoria com áreas de prática, equipa, análises e contacto confidencial.",
    capability: "Áreas de prática, perfis de sócios, filtros de análises, escritórios e pedido confidencial.",
    proof: "Prévia do site ao vivo · 10 controlos locais · contacto de demonstração atento à privacidade",
  },
  "velora-commerce": {
    title: "Coleção de produtos premium",
    kind: "Site de comércio eletrónico",
    prompt: "Cria um site de comércio eletrónico refinado com coleções, materiais, configuração de produto e carrinho de demonstração.",
    capability: "Filtros de coleção, história do produto, escolha de cor, quantidade, carrinho e estimativa de envio.",
    proof: "Prévia do site ao vivo · 13 controlos locais · carrinho simulado sem pagamento",
  },
  "festival-onda": {
    title: "Cultura e programa ao vivo",
    kind: "Site para festivais e eventos",
    prompt: "Cria um site cultural arrojado com programa, palcos, artistas, agenda pessoal e informações de bilhetes.",
    capability: "Filtros do programa, mapa de palcos, fichas de artistas, agenda pessoal e informações de bilhetes.",
    proof: "Prévia do site ao vivo · 12 controlos locais · agenda do festival offline",
  },
});

const TABLES: Record<Locale, FlagshipCopyTable> = { en, it, es, fr, de, pt };

const LABELS: Record<Locale, ShowcaseLabels> = {
  en: {
    prompt: "Original prompt",
    capability: "Capability proof",
    proof: "Evidence",
    all: "All 18",
    apps: "Apps & software · 9",
    sites: "Websites · 9",
    appsTitle: "Apps and operational software",
    appsLead: "Nine interactive products for work, data, appointments and complex operations.",
    sitesTitle: "Websites",
    sitesLead: "Andrea’s real sites first, then sector demos for professional services, hospitality, health, commerce and culture.",
    projectsCount: "18 live projects",
    archiveTitle: "More examples",
    archiveLead: "Earlier experiments remain available as an archive; they are separate from the eighteen flagship projects.",
    archiveOpen: "Open archived example",
  },
  it: {
    prompt: "Prompt originale",
    capability: "Capacità dimostrata",
    proof: "Prova",
    all: "Tutti · 18",
    apps: "App e programmi · 9",
    sites: "Siti · 9",
    appsTitle: "App e software operativi",
    appsLead: "Nove prodotti interattivi per lavoro, dati, appuntamenti e operazioni complesse.",
    sitesTitle: "Siti",
    sitesLead: "In cima i siti reali di Andrea; sotto restano i settori dimostrativi.",
    projectsCount: "18 progetti live",
    archiveTitle: "Altri esempi",
    archiveLead: "Gli esperimenti precedenti restano disponibili in archivio, separati dai diciotto progetti principali.",
    archiveOpen: "Apri esempio archiviato",
  },
  es: {
    prompt: "Prompt original",
    capability: "Capacidad demostrada",
    proof: "Evidencia",
    all: "Todos · 18",
    apps: "Apps y software · 9",
    sites: "Sitios · 9",
    appsTitle: "Apps y software operativo",
    appsLead: "Nueve productos interactivos para trabajo, datos, citas y operaciones complejas.",
    sitesTitle: "Sitios",
    sitesLead: "Primero los sitios reales de Andrea; después los demos por sector.",
    projectsCount: "18 proyectos en vivo",
    archiveTitle: "Más ejemplos",
    archiveLead: "Los experimentos anteriores siguen disponibles en un archivo separado de los dieciocho proyectos principales.",
    archiveOpen: "Abrir ejemplo archivado",
  },
  fr: {
    prompt: "Prompt original",
    capability: "Capacité démontrée",
    proof: "Preuve",
    all: "Tous · 18",
    apps: "Apps et logiciels · 9",
    sites: "Sites · 9",
    appsTitle: "Applications et logiciels métier",
    appsLead: "Neuf produits interactifs pour le travail, les données, les rendez-vous et les opérations complexes.",
    sitesTitle: "Sites",
    sitesLead: "D’abord les vrais sites d’Andrea, puis les démos par secteur.",
    projectsCount: "18 projets en direct",
    archiveTitle: "Plus d’exemples",
    archiveLead: "Les expériences précédentes restent disponibles dans une archive séparée des dix-huit projets principaux.",
    archiveOpen: "Ouvrir l’exemple archivé",
  },
  de: {
    prompt: "Original-Prompt",
    capability: "Gezeigte Fähigkeit",
    proof: "Nachweis",
    all: "Alle · 18",
    apps: "Apps und Software · 9",
    sites: "Websites · 9",
    appsTitle: "Apps und operative Software",
    appsLead: "Neun interaktive Produkte für Arbeit, Daten, Termine und komplexe Abläufe.",
    sitesTitle: "Websites",
    sitesLead: "Zuerst Andreas echte Sites, danach die Branchen-Demos.",
    projectsCount: "18 Live-Projekte",
    archiveTitle: "Weitere Beispiele",
    archiveLead: "Frühere Experimente bleiben in einem separaten Archiv neben den achtzehn Hauptprojekten verfügbar.",
    archiveOpen: "Archiviertes Beispiel öffnen",
  },
  pt: {
    prompt: "Prompt original",
    capability: "Capacidade demonstrada",
    proof: "Evidência",
    all: "Todos · 18",
    apps: "Apps e software · 9",
    sites: "Sites · 9",
    appsTitle: "Apps e software operacional",
    appsLead: "Nove produtos interativos para trabalho, dados, agendas e operações complexas.",
    sitesTitle: "Sites",
    sitesLead: "Primeiro os sites reais do Andrea; depois as demos por setor.",
    projectsCount: "18 projetos ao vivo",
    archiveTitle: "Mais exemplos",
    archiveLead: "Experimentos anteriores permanecem em um arquivo separado dos dezoito projetos principais.",
    archiveOpen: "Abrir exemplo arquivado",
  },
};

export function flagshipCopy(locale: Locale, id: FlagshipId): FlagshipCopy {
  return TABLES[locale][id];
}

export function flagshipShowcaseLabels(locale: Locale): ShowcaseLabels {
  return LABELS[locale];
}
