/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TryRouteImport } from './routes/try'
import { Route as VetrinaRouteImport } from './routes/vetrina'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as TCodeRouteImport } from './routes/t.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as StudioIdLaunchRouteImport } from './routes/studio.$id.launch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const VetrinaRoute = VetrinaRouteImport.update({
  id: '/vetrina',
  path: '/vetrina',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioRoute,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIdLaunchRoute = StudioIdLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => StudioIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRouteWithChildren
  '/try': typeof TryRoute
  '/vetrina': typeof VetrinaRoute
  '/a/$slug': typeof ASlugRoute
  '/studio/$id': typeof StudioIdRouteWithChildren
  '/t/$code': typeof TCodeRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/$id/launch': typeof StudioIdLaunchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/try': typeof TryRoute
  '/vetrina': typeof VetrinaRoute
  '/a/$slug': typeof ASlugRoute
  '/studio/$id': typeof StudioIdRouteWithChildren
  '/t/$code': typeof TCodeRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/$id/launch': typeof StudioIdLaunchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRouteWithChildren
  '/try': typeof TryRoute
  '/vetrina': typeof VetrinaRoute
  '/a/$slug': typeof ASlugRoute
  '/studio/$id': typeof StudioIdRouteWithChildren
  '/t/$code': typeof TCodeRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/$id/launch': typeof StudioIdLaunchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/go-live'
    | '/login'
    | '/pricing'
    | '/studio'
    | '/try'
    | '/vetrina'
    | '/a/$slug'
    | '/studio/$id'
    | '/t/$code'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/$id/launch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/go-live'
    | '/login'
    | '/pricing'
    | '/try'
    | '/vetrina'
    | '/a/$slug'
    | '/studio/$id'
    | '/t/$code'
    | '/studio'
    | '/api/auth/$'
    | '/studio/$id/launch'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/go-live'
    | '/login'
    | '/pricing'
    | '/studio'
    | '/try'
    | '/vetrina'
    | '/a/$slug'
    | '/studio/$id'
    | '/t/$code'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/$id/launch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GoLiveRoute: typeof GoLiveRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  StudioRoute: typeof StudioRouteWithChildren
  TryRoute: typeof TryRoute
  VetrinaRoute: typeof VetrinaRoute
  ASlugRoute: typeof ASlugRoute
  TCodeRoute: typeof TCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vetrina': {
      id: '/vetrina'
      path: '/vetrina'
      fullPath: '/vetrina'
      preLoaderRoute: typeof VetrinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$id/launch': {
      id: '/studio/$id/launch'
      path: '/launch'
      fullPath: '/studio/$id/launch'
      preLoaderRoute: typeof StudioIdLaunchRouteImport
      parentRoute: typeof StudioIdRoute
    }
  }
}

interface StudioIdRouteChildren {
  StudioIdLaunchRoute: typeof StudioIdLaunchRoute
}

const StudioIdRouteChildren: StudioIdRouteChildren = {
  StudioIdLaunchRoute: StudioIdLaunchRoute,
}

const StudioIdRouteWithChildren = StudioIdRoute._addFileChildren(
  StudioIdRouteChildren,
)

interface StudioRouteChildren {
  StudioIdRoute: typeof StudioIdRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIdRoute: StudioIdRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GoLiveRoute: GoLiveRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  StudioRoute: StudioRouteWithChildren,
  TryRoute: TryRoute,
  VetrinaRoute: VetrinaRoute,
  ASlugRoute: ASlugRoute,
  TCodeRoute: TCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
